"""Initial tables

Revision ID: 027ab562154f
Revises: 85b3bcd78a63
Create Date: 2025-08-05 03:05:33.658847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027ab562154f'
down_revision: Union[str, Sequence[str], None] = '85b3bcd78a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_users', 'purpose',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('todo_users', 'mobile_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_users', 'mobile_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('todo_users', 'purpose',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
