"""Added due date and summary fied

Revision ID: 28005ce6c41f
Revises: ba328d41a438
Create Date: 2025-08-05 03:22:00.097788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28005ce6c41f'
down_revision: Union[str, Sequence[str], None] = 'ba328d41a438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('finish_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'finish_note')
    # ### end Alembic commands ###
