"""Initial tables

Revision ID: 3d7de13188f1
Revises: ac12d748945e
Create Date: 2025-07-25 18:10:11.076295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7de13188f1'
down_revision: Union[str, Sequence[str], None] = 'ac12d748945e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('todos_user_id_fkey'), 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todo_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key(op.f('todos_user_id_fkey'), 'todos', 'todo_users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
