"""Initial tables

Revision ID: 85b3bcd78a63
Revises: 9bb25ec46727
Create Date: 2025-08-05 03:04:00.013454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b3bcd78a63'
down_revision: Union[str, Sequence[str], None] = '9bb25ec46727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_users', sa.Column('purpose', sa.String(), nullable=True))
    op.add_column('todo_users', sa.Column('mobile_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_users', 'mobile_no')
    op.drop_column('todo_users', 'purpose')
    # ### end Alembic commands ###
