"""Initial tables

Revision ID: a174133d4a6f
Revises: 3d7de13188f1
Create Date: 2025-07-25 18:11:12.342577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a174133d4a6f'
down_revision: Union[str, Sequence[str], None] = '3d7de13188f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('todos_user_id_fkey'), 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todo_users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key(op.f('todos_user_id_fkey'), 'todos', 'todo_users', ['user_id'], ['id'])
    # ### end Alembic commands ###
